// MININONOGRAM — tap-to-paint nonogram. The puzzle itself is never
// hand-authored: nonogram_data.js carries precomputed per-pixel data for
// every sprite (generated by ../scripts_gen_nonogram_data.ps1). Decoding
// pixels at runtime via canvas would need drawImage+getImageData, but
// Chrome taints the canvas for an <img> loaded from a separate file://
// resource, so that throws a SecurityError under file:// — hence the
// precompute step instead.

const DIFFICULTY_TAGS = ['tiny', 'small', 'medium', 'large'];
const MIN_CELL_PX = 14;
const MAX_CELL_PX = 44;
const GRID_GAP_PX = 1;
const GROUP_EXTRA_PX = 1;

const Game = {
    id: 'MININONOGRAM',
    i18n: {},
    assets: {},
    stats: {},
    levelOptions: {},
    markMode: false,
    puzzle: null,
    startTime: 0,
    elapsedSeconds: 0,
    dragState: null,
    suppressNextClick: false,

    init: async function(config = {}) {
        const languageKey = Utils.getPreferredLanguage(config.languageKey || 'en_US');
        const assetsPath = config.assetsPath || (window.location.href.substring(0, window.location.href.lastIndexOf('/')) + '/');

        const assets = await Utils.loadScript(assetsPath + 'assets.js', 'assets') || [];
        this.i18n = await Utils.loadLanguageBundle(assetsPath, languageKey);
        await Utils.loadScript(assetsPath + 'dailyChallenges.js', 'dailyChallenges');
        const nonogramData = await Utils.loadScript(assetsPath + 'nonogram_data.js', 'nonogram_data') || [];

        this.assetsPath = assetsPath;
        this.assets = assets;
        this.tileSrc = {
            empty: assetsPath + assets.find(a => a.id === 'tile_unpressed').src,
            filled: assetsPath + assets.find(a => a.id === 'tile_pressed').src,
            note: assetsPath + assets.find(a => a.id === 'tile_marked').src,
        };
        this.nonogramById = {};
        nonogramData.forEach(entry => { this.nonogramById[entry.id] = entry; });
        this.stats = config.stats || JSON.parse(localStorage.getItem(this.id + '/stats')) || {};

        await Utils.preloadAssets(assets);
        Utils.setBackground(assets.find(a => a.id === 'bg'));
        Utils.applyLocalization(this.i18n);
        Utils.setupLanguageSwitcher(languageKey, (newKey) => this.changeLanguage(newKey));
        Utils.setupMuteButton();
        Utils.switchScreen('loading-screen', 'title-screen');

        window.addEventListener('resize', () => { if (this.puzzle) this.renderGrid(); });

        // Drag/swipe-to-paint: pointermove doesn't retarget to whatever
        // element is currently under a touch pointer (touch implicitly
        // captures to the element from pointerdown), so elementFromPoint
        // is used instead to find the cell actually under the finger/mouse
        // on every move, regardless of which element started the gesture.
        window.addEventListener('pointermove', (e) => this.continueCellDrag(e.clientX, e.clientY));
        window.addEventListener('pointerup', () => this.endCellDrag());
        window.addEventListener('pointercancel', () => this.endCellDrag());

        Utils.listenForHostCommands({ onStartLevel: () => this.startLevel() });
        Utils.notifyReady();
    },

    changeLanguage: async function(languageKey) {
        this.i18n = await Utils.loadLanguageBundle(this.assetsPath, languageKey);
        Utils.applyLocalization(this.i18n);
        Utils.setPreferredLanguage(languageKey);
        Utils.syncLanguageSwitcher(languageKey);
    },

    // The title screen's PLAY button is a quick-play shortcut: it skips
    // the level picker but still keeps things quick, so it only draws
    // from the two smallest tiers, never MEDIUM/LARGE.
    startQuickPlay: function() {
        const difficulty = Math.random() < 0.5 ? 'tiny' : 'small';
        this.startLevel({ difficulty });
    },

    startDaily: function() {
        const now = new Date();
        const todayStr = now.toISOString().split('T')[0];
        window.todayStr = todayStr;
        const challenges = window.dailyChallenges || {};
        const keys = Object.keys(challenges);
        let assetId = challenges[todayStr];
        if (!assetId && keys.length > 0) {
            const start = new Date(now.getFullYear(), 0, 0);
            const dayOfYear = Math.floor((now - start) / (1000 * 60 * 60 * 24));
            assetId = challenges[keys[dayOfYear % keys.length]];
        }
        this.startLevel({ difficulty: 'large', assetId, daily: true });
    },

    startLevel: function(options = {}) {
        const difficulty = DIFFICULTY_TAGS.includes(options.difficulty) ? options.difficulty : 'small';
        const pool = this.assets.filter(a => a.type === 'image' && Array.isArray(a.tags) && a.tags.includes(difficulty) && this.nonogramById[a.id]);
        const asset = (options.assetId && pool.find(a => a.id === options.assetId)) || pool[Math.floor(Math.random() * pool.length)];
        if (!asset) return;

        this.levelOptions = { difficulty, assetId: asset.id, daily: !!options.daily };
        this.markMode = false;
        this.updateMarkToggleButton();

        Utils.switchScreen('title-screen', 'game-screen');
        Utils.switchScreen('level-screen', 'game-screen');

        this.puzzle = this.buildPuzzle(this.nonogramById[asset.id], asset);
        this.startTime = performance.now();
        this.renderGrid();
    },

    // Turns the sprite's precomputed pixel string into a boolean solution
    // grid. Whichever opaque ink color (pure white or pure black) covers
    // more pixels becomes the "painted" color for this puzzle — the other
    // ink color and transparency both count as background.
    buildPuzzle: function(pixelData, asset) {
        const cols = pixelData.w;
        const rows = pixelData.h;
        const chars = pixelData.data;

        let whiteCount = 0, blackCount = 0;
        for (let i = 0; i < chars.length; i++) {
            if (chars[i] === '1') whiteCount++;
            else if (chars[i] === '0') blackCount++;
        }
        const paintedChar = whiteCount >= blackCount ? '1' : '0';

        const solution = [];
        for (let r = 0; r < rows; r++) {
            const rowVals = [];
            for (let c = 0; c < cols; c++) {
                rowVals.push(chars[r * cols + c] === paintedChar);
            }
            solution.push(rowVals);
        }

        const rowHints = solution.map(row => this.lineHints(row));
        const colHints = [];
        for (let c = 0; c < cols; c++) colHints.push(this.lineHints(solution.map(row => row[c])));

        return {
            asset, cols, rows, solution, rowHints, colHints,
            state: solution.map(row => row.map(() => 'empty')),
        };
    },

    // Run-lengths of consecutive painted cells along one row/column, in
    // order — the classic nonogram clue. An empty line shows a single 0.
    lineHints: function(line) {
        const groups = [];
        let run = 0;
        for (const on of line) {
            if (on) run++;
            else { if (run > 0) groups.push(run); run = 0; }
        }
        if (run > 0) groups.push(run);
        return groups.length ? groups : [0];
    },

    toggleMarkMode: function() {
        this.markMode = !this.markMode;
        this.updateMarkToggleButton();
    },

    updateMarkToggleButton: function() {
        const btn = document.getElementById('mark-toggle-btn');
        btn.classList.toggle('is-active', this.markMode);
        btn.setAttribute('aria-pressed', String(this.markMode));
        document.getElementById('mark-mode-label').style.display = this.markMode ? '' : 'none';
    },

    showInstructions: function() { document.getElementById('instructions-modal').classList.add('active'); },
    hideInstructions: function() { document.getElementById('instructions-modal').classList.remove('active'); },

    // Mistakes are real and silent: tapping just swaps a cell between
    // painted and unpainted, right or wrong, with no rejection or red
    // flash. The only feedback is the win check below, which requires an
    // exact match. With the mark toggle on, tapping instead toggles the
    // mark itself (marked -> unmarked, anything else -> marked) — marks
    // count as "off" everywhere else, so a marked cell is just an
    // unpainted one with a reminder on it.
    nextCellState: function(cellState) {
        if (this.markMode) return cellState === 'note' ? 'empty' : 'note';
        return cellState === 'filled' ? 'empty' : 'filled';
    },

    // A single discrete tap (mouse click, or Enter/Space on a focused
    // cell for keyboard users) — not a drag. Skipped once for the cell a
    // drag gesture just finished on, since that cell's change was already
    // applied live during the drag; see endCellDrag.
    handleCellTap: function(r, c) {
        if (this.suppressNextClick) { this.suppressNextClick = false; return; }
        const p = this.puzzle;
        p.state[r][c] = this.nextCellState(p.state[r][c]);
        this.afterCellChange();
    },

    afterCellChange: function() {
        if (window.audio?.click) Utils.playSound(window.audio.click);
        this.renderGrid();
        if (this.isSolved()) this.finishLevel();
    },

    // Drag/swipe painting: pointerdown just arms a possible drag without
    // changing anything yet, so a plain tap with no movement still goes
    // through the ordinary click -> handleCellTap path (keeping keyboard
    // activation, which never fires pointerdown, working unchanged).
    beginCellDrag: function(r, c) {
        this.dragState = { active: false, startR: r, startC: c, value: null, visited: new Set() };
    },

    continueCellDrag: function(clientX, clientY) {
        if (!this.dragState) return;
        const el = document.elementFromPoint(clientX, clientY);
        if (!el || !el.classList.contains('nono-cell')) return;
        const r = parseInt(el.dataset.r, 10);
        const c = parseInt(el.dataset.c, 10);

        if (!this.dragState.active) {
            // The first move confirms this is a real drag. Lock in one
            // value from the starting cell and paint the whole stroke with
            // it, rather than toggling each cell it crosses individually —
            // otherwise a drag back and forth over the same cells would
            // flicker them on and off instead of just selecting them.
            this.dragState.active = true;
            const p = this.puzzle;
            this.dragState.value = this.nextCellState(p.state[this.dragState.startR][this.dragState.startC]);
            this.applyDragValue(this.dragState.startR, this.dragState.startC);
        }
        this.applyDragValue(r, c);
    },

    applyDragValue: function(r, c) {
        const key = r + ',' + c;
        if (this.dragState.visited.has(key)) return;
        this.dragState.visited.add(key);
        const p = this.puzzle;
        if (p.state[r][c] === this.dragState.value) return;
        p.state[r][c] = this.dragState.value;
        this.afterCellChange();
    },

    endCellDrag: function() {
        if (!this.dragState) return;
        if (this.dragState.active) {
            // The gesture's trailing click event (fired right after
            // pointerup, on whatever cell the pointer ends up over) would
            // otherwise re-toggle a cell the drag already changed. If the
            // pointer was released off the grid entirely, no click ever
            // fires to consume this flag, so it's cleared on a timeout too.
            this.suppressNextClick = true;
            setTimeout(() => { this.suppressNextClick = false; }, 0);
        }
        this.dragState = null;
    },

    isSolved: function() {
        const p = this.puzzle;
        return p.solution.every((row, r) => row.every((on, c) => (p.state[r][c] === 'filled') === on));
    },

    // A row/column is "done" only once it's an exact match — every
    // solution cell painted and nothing extra — used solely to dim its
    // clue numbers, never to block or hint.
    lineDone: function(solutionLine, stateLine) {
        return solutionLine.every((on, i) => (stateLine[i] === 'filled') === on);
    },

    // KNOWN LIMITATION, not addressed yet: a puzzle much wider than it is
    // tall (e.g. 16x5) on a narrow portrait phone can still end up with
    // very small cells, since availableWidth is capped far more tightly
    // than availableHeight in that orientation. Ideas if this needs
    // revisiting:
    //   - A one-time "rotate your phone" hint for puzzles above some
    //     width:height ratio, rather than forcing landscape.
    //   - Let the *hint* number tracks shrink below MIN_CELL_PX on their
    //     own (they only need to fit tabular-nums digits, not be tapped),
    //     reclaiming width for the actual tappable puzzle cells.
    //   - Pinch-to-zoom/pan just the grid container instead of fitting the
    //     whole puzzle on screen at once — a bigger change, but the only
    //     option that doesn't shrink cells below a comfortable tap target.
    renderGrid: function() {
        const p = this.puzzle;
        if (!p) return;

        const hintCols = Math.max(...p.rowHints.map(h => h.length));
        const hintRows = Math.max(...p.colHints.map(h => h.length));
        const totalCols = hintCols + p.cols;
        const totalRows = hintRows + p.rows;

        const container = document.getElementById('nonogram-grid');
        const gameScreen = document.getElementById('game-screen');
        const topbar = gameScreen.querySelector('.cf-topbar');
        const stage = document.getElementById('nonogram-stage');
        const toolbar = document.getElementById('nono-toolbar');
        const screenStyle = getComputedStyle(gameScreen);
        const topbarStyle = getComputedStyle(topbar);
        const stageStyle = getComputedStyle(stage);

        // Reserved space comes only from the topbar's and toolbar's own
        // intrinsic sizes (offsetHeight + margins/gap), never from the
        // grid container's current position — reading the grid's own
        // getBoundingClientRect() would be circular, since resizing the
        // grid shifts where it sits (the screen body centers its content),
        // which would then feed a wrong measurement into the next resize,
        // growing over several taps instead of being correct on the very
        // first render.
        const stageGap = parseFloat(stageStyle.rowGap) || 0;
        const reservedHeight = topbar.offsetHeight + parseFloat(topbarStyle.marginBottom)
            + parseFloat(screenStyle.paddingTop) + parseFloat(screenStyle.paddingBottom)
            + toolbar.offsetHeight + stageGap;

        const availableWidth = Math.min(window.innerWidth * 0.94, 640);
        const availableHeight = Math.max(160, window.innerHeight - reservedHeight);
        const colGapTotal = GRID_GAP_PX * (totalCols - 1);
        const rowGapTotal = GRID_GAP_PX * (totalRows - 1);
        // Floored to a whole pixel, same reasoning as before, but the real
        // fix is the explicit `gap` below: two adjacent tracks sized and
        // positioned independently can still land a fraction of a device
        // pixel apart at some zoom/DPI combos, which reads as either a
        // hairline gap or an overlap depending on which way it rounds. A
        // deliberate empty gap between every track means that same rounding
        // wobble only ever makes the gap a bit bigger or smaller — it can
        // never produce an overlap, since there's real empty space there.
        const cellSize = Math.floor(Math.max(MIN_CELL_PX, Math.min(MAX_CELL_PX, (availableWidth - colGapTotal) / totalCols, (availableHeight - rowGapTotal) / totalRows)));
        const fontSize = Math.max(13, cellSize * 0.66);

        container.style.gap = GRID_GAP_PX + 'px';
        container.style.gridTemplateColumns = `repeat(${totalCols}, ${cellSize}px)`;
        container.style.gridTemplateRows = `repeat(${totalRows}, ${cellSize}px)`;
        container.style.width = (cellSize * totalCols + colGapTotal) + 'px';
        container.style.height = (cellSize * totalRows + rowGapTotal) + 'px';
        container.innerHTML = '';

        const colDone = [];
        for (let c = 0; c < p.cols; c++) {
            colDone.push(this.lineDone(p.solution.map(row => row[c]), p.state.map(row => row[c])));
        }

        for (let gr = 0; gr < totalRows; gr++) {
            for (let gc = 0; gc < totalCols; gc++) {
                let el;
                if (gr < hintRows && gc < hintCols) {
                    el = document.createElement('div'); // corner spacer
                } else if (gr < hintRows && gc >= hintCols) {
                    const c = gc - hintCols;
                    const hints = p.colHints[c];
                    const pad = hintRows - hints.length;
                    el = document.createElement('div');
                    el.className = 'nono-hint';
                    if (gr >= pad) {
                        el.textContent = hints[gr - pad];
                        if (colDone[c]) el.classList.add('is-done');
                    }
                } else if (gr >= hintRows && gc < hintCols) {
                    const r = gr - hintRows;
                    const hints = p.rowHints[r];
                    const pad = hintCols - hints.length;
                    el = document.createElement('div');
                    el.className = 'nono-hint';
                    if (gc >= pad) {
                        el.textContent = hints[gc - pad];
                        if (this.lineDone(p.solution[r], p.state[r])) el.classList.add('is-done');
                    }
                } else {
                    const r = gr - hintRows;
                    const c = gc - hintCols;
                    el = document.createElement('button');
                    const state = p.state[r][c];
                    el.className = 'nono-cell';
                    el.style.backgroundImage = `url('${this.tileSrc[state]}')`;
                    // Every 5th row/column (from the top-left) gets one
                    // extra pixel on top of the grid's baseline 1px gap, as
                    // a pure visual counting aid — shrinks that cell within
                    // its fixed-size grid track rather than resizing the
                    // grid itself.
                    if (c > 0 && c % 5 === 0) el.style.marginLeft = GROUP_EXTRA_PX + 'px';
                    if (r > 0 && r % 5 === 0) el.style.marginTop = GROUP_EXTRA_PX + 'px';
                    el.setAttribute('aria-label', `${this.i18n['SR_ROW'] || 'Row'} ${r + 1}, ${this.i18n['SR_COL'] || 'Column'} ${c + 1}`);
                    // dataset r/c let continueCellDrag identify a cell found
                    // via elementFromPoint; pointerdown arms a possible drag
                    // (see beginCellDrag), onclick still handles a plain tap.
                    el.dataset.r = r;
                    el.dataset.c = c;
                    el.onpointerdown = (e) => { e.preventDefault(); this.beginCellDrag(r, c); };
                    el.onclick = () => this.handleCellTap(r, c);
                    container.appendChild(el);
                    continue;
                }
                el.style.fontSize = fontSize + 'px';
                container.appendChild(el);
            }
        }
    },

    finishLevel: function() {
        this.elapsedSeconds = (performance.now() - this.startTime) / 1000;

        const key = 'bestTime_' + this.levelOptions.difficulty;
        this.stats[key] = this.stats[key] ? Math.min(this.stats[key], this.elapsedSeconds) : this.elapsedSeconds;
        this.stats.gamesCompleted = (this.stats.gamesCompleted || 0) + 1;
        if (this.levelOptions.daily) {
            this.stats.dailyChallengesDates = this.stats.dailyChallengesDates || [];
            this.stats.dailyChallengesDates = Utils.simpleUniqueArray([...this.stats.dailyChallengesDates, window.todayStr]);
            this.stats.dailyChallengesCompleted = this.stats.dailyChallengesDates.length;
        }
        localStorage.setItem(this.id + '/stats', JSON.stringify(this.stats));
        Utils.finishGame(this.levelOptions, { seconds: this.elapsedSeconds });

        if (window.audio?.win) Utils.playSound(window.audio.win);
        this.showResult();
    },

    showResult: function() {
        const isDaily = !!this.levelOptions.daily;
        const asset = this.puzzle.asset;
        document.getElementById('result-image').src = this.assetsPath + asset.src;
        document.getElementById('result-time').innerText = Utils.formatTime(this.elapsedSeconds);
        document.getElementById('result-share').style.display = isDaily ? '' : 'none';
        document.getElementById('result-play-again-actions').style.display = isDaily ? 'none' : '';
        document.getElementById('result-continue-actions').style.display = isDaily ? '' : 'none';
        document.getElementById('result-modal').classList.add('active');
    },

    // Not offered after a daily challenge — there's only one per day. Omits
    // assetId so a fresh random puzzle of the same difficulty is picked,
    // instead of re-solving the one that was just completed.
    playAgain: function() {
        document.getElementById('result-modal').classList.remove('active');
        this.startLevel({ difficulty: this.levelOptions.difficulty });
    },

    copyShareText: function() {
        const template = this.i18n['SHARE_TEMPLATE'] || 'Mini Nonogram {date}: solved in {time}';
        const text = Utils.formatTemplate(template, {
            date: window.todayStr || '',
            time: Utils.formatTime(this.elapsedSeconds),
        });
        Utils.copyToClipboard(text).then(ok => {
            const btn = document.getElementById('share-copy-btn');
            if (!btn || !ok) return;
            const original = btn.innerText;
            btn.innerText = this.i18n['BTN_COPIED'] || 'COPIED!';
            setTimeout(() => { btn.innerText = original; }, 1500);
        });
    },

    acknowledgeResult: function() {
        document.getElementById('result-modal').classList.remove('active');
        this.quit();
    },

    quit: function() {
        this.puzzle = null;
        Utils.switchScreen('game-screen', 'title-screen');
        Utils.switchScreen('level-screen', 'title-screen');
    },

    requestQuit: function() { document.getElementById('quit-modal').classList.add('active'); },
    cancelQuit: function() { document.getElementById('quit-modal').classList.remove('active'); },
    confirmQuit: function() {
        document.getElementById('quit-modal').classList.remove('active');
        this.quit();
    },

    showStats: function() {
        document.getElementById('stat-games-completed').innerText = this.stats.gamesCompleted || 0;
        document.getElementById('stat-dailies-completed').innerText = this.stats.dailyChallengesCompleted || 0;
        document.getElementById('stat-best-tiny').innerText = this.stats.bestTime_tiny ? Utils.formatTime(this.stats.bestTime_tiny) : '—';
        document.getElementById('stat-best-small').innerText = this.stats.bestTime_small ? Utils.formatTime(this.stats.bestTime_small) : '—';
        document.getElementById('stat-best-medium').innerText = this.stats.bestTime_medium ? Utils.formatTime(this.stats.bestTime_medium) : '—';
        document.getElementById('stat-best-large').innerText = this.stats.bestTime_large ? Utils.formatTime(this.stats.bestTime_large) : '—';
        Utils.switchScreen('title-screen', 'stats-screen');
    }
};

document.addEventListener('DOMContentLoaded', () => Game.init());
